package com.reevajs.reeva.runtime.builtins

import com.reevajs.reeva.runtime.JSValue
import com.reevajs.reeva.runtime.collections.*
import com.reevajs.reeva.runtime.objects.PropertyKey
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodType

internal enum class Builtin(val jsName: String, val type: Type = Type.Normal) {
    ArrayCtorGetSymbolSpecies("@@species", type = Type.Getter),
    ArrayCtorIsArray("isArray"),
    ArrayCtorFrom("from"),
    ArrayCtorOf("of"),
    ArrayProtoAt("at"),
    ArrayProtoConcat("concat"),
    ArrayProtoCopyWithin("copyWithin"),
    ArrayProtoEntries("entries"),
    ArrayProtoEvery("every"),
    ArrayProtoFill("fill"),
    ArrayProtoFilter("filter"),
    ArrayProtoFind("find"),
    ArrayProtoFindIndex("findIndex"),
    ArrayProtoFlat("flat"),
    ArrayProtoFlatMap("flatMap"),
    ArrayProtoForEach("forEach"),
    ArrayProtoIncludes("includes"),
    ArrayProtoIndexOf("indexOf"),
    ArrayProtoJoin("join"),
    ArrayProtoKeys("keys"),
    ArrayProtoLastIndexOf("lastIndexOf"),
    ArrayProtoMap("map"),
    ArrayProtoPop("pop"),
    ArrayProtoPush("push"),
    ArrayProtoReduce("reduce"),
    ArrayProtoReduceRight("reduceRight"),
    ArrayProtoReverse("reverse"),
    ArrayProtoShift("shift"),
    ArrayProtoSlice("slice"),
    ArrayProtoSome("some"),
    ArrayProtoSplice("splice"),
    ArrayProtoToString("toString"),
    ArrayProtoUnshift("unshift"),
    ArrayProtoValues("values"),

    ArrayBufferCtorIsView("isView"),
    ArrayBufferCtorGetSymbolSpecies("@@species", type = Type.Getter),
    ArrayBufferProtoGetByteLength("byteLength", type = Type.Getter),
    ArrayBufferProtoSlice("slice"),

    ArrayIteratorProtoNext("next"),

    BigIntCtorAsIntN("asIntN"),
    BigIntCtorAsUintN("asUintN"),
    BigIntProtoToString("toString"),
    BigIntProtoValueOf("valueOf"),

    BooleanProtoToString("toString"),
    BooleanProtoValueOf("valueOf"),

    DataViewProtoGetBuffer("buffer", type = Type.Getter),
    DataViewProtoGetByteLength("byteLength", type = Type.Getter),
    DataViewProtoGetByteOffset("byteOffset", type = Type.Getter),
    DataViewProtoGetBigInt64("getBigInt64"),
    DataViewProtoGetBigUint64("getBigUint64"),
    DataViewProtoGetFloat32("getFloat32"),
    DataViewProtoGetFloat64("getFloat64"),
    DataViewProtoGetInt8("getInt8"),
    DataViewProtoGetInt16("getInt16"),
    DataViewProtoGetInt32("getInt32"),
    DataViewProtoGetUint8("getUint8"),
    DataViewProtoGetUint16("getUint16"),
    DataViewProtoGetUint32("getUint32"),
    DataViewProtoSetBigInt64("setBigInt64"),
    DataViewProtoSetBigUint64("setBigUint64"),
    DataViewProtoSetFloat32("setFloat32"),
    DataViewProtoSetFloat64("setFloat64"),
    DataViewProtoSetInt8("setInt8"),
    DataViewProtoSetInt16("setInt16"),
    DataViewProtoSetInt32("setInt32"),
    DataViewProtoSetUint8("setUint8"),
    DataViewProtoSetUint16("setUint16"),
    DataViewProtoSetUint32("setUint32"),

    DateCtorNow("now"),
    DateCtorParse("parse"),
    DateCtorUTC("utc"),
    DateProtoGetDate("getDate"),
    DateProtoGetDay("getDay"),
    DateProtoGetFullYear("getFullYear"),
    DateProtoGetHours("getHours"),
    DateProtoGetMilliseconds("getMilliseconds"),
    DateProtoGetMinutes("getMinutes"),
    DateProtoGetMonth("getMonth"),
    DateProtoGetSeconds("getSeconds"),
    DateProtoGetTime("getTime"),
    DateProtoGetTimezoneOffset("getTimezoneOffset"),
    DateProtoGetUTCDate("getUTCDate"),
    DateProtoGetUTCFullYear("getUTCFullYear"),
    DateProtoGetUTCHours("getUTCHours"),
    DateProtoGetUTCMilliseconds("getUTCMilliseconds"),
    DateProtoGetUTCMinutes("getUTCMinutes"),
    DateProtoGetUTCMonth("getUTCMonth"),
    DateProtoGetUTCSeconds("getUTCSeconds"),
    DateProtoSetDate("setDate"),
    DateProtoSetFullYear("setFullYear"),
    DateProtoSetHours("setHours"),
    DateProtoSetMilliseconds("setMilliseconds"),
    DateProtoSetMonth("setMonth"),
    DateProtoSetSeconds("setSeconds"),
    DateProtoSetTime("setTime"),
    DateProtoSetUTCDate("setUTCDate"),
    DateProtoSetUTCFullYear("setUTCFullYear"),
    DateProtoSetUTCHours("setUTCHours"),
    DateProtoSetUTCMilliseconds("setUTCMilliseconds"),
    DateProtoSetUTCMinutes("setUTCMinutes"),
    DateProtoSetUTCMonth("setUTCMonth"),
    DateProtoSetUTCSeconds("setUTCSeconds"),
    DateProtoToDateString("toDateString"),
    DateProtoToISOString("toISOString"),
    DateProtoToJSON("toJSON"),
    DateProtoToString("toString"),
    DateProtoToTimeString("toTimeString"),
    DateProtoToUTCString("toUTCString"),
    DateProtoValueOf("valueOf"),
    DateProtoSymbolToPrimitive("@@toPrimitive"),

    ErrorProtoToString("toString"),

    FunctionProtoApply("apply"),
    FunctionProtoBind("bind"),
    FunctionProtoCall("call"),

    GeneratorObjectProtoNext("next"),
    GeneratorObjectProtoReturn("return"),
    GeneratorObjectProtoThrow("throw"),

    GlobalEval("eval"),
    GlobalParseInt("parseInt"),

    IteratorProtoSymbolIterator("@@iterator"),

    JSONParse("parse"),
    JSONStringify("stringify"),
    JSONGetSymbolToStringTag("@@toStringTag", type = Type.Getter),

    ListIteratorProtoNext("next"),

    MapCtorGetSymbolSpecies("@@species", type = Type.Getter),
    MapProtoClear("clear"),
    MapProtoDelete("delete"),
    MapProtoEntries("entries"),
    MapProtoForEach("forEach"),
    MapProtoGet("get"),
    MapProtoHas("has"),
    MapProtoKeys("keys"),
    MapProtoSet("set"),
    MapProtoValues("values"),
    MapProtoGetSize("size", type = Type.Getter),

    MapIteratorProtoNext("next"),

    MathAbs("abs"),
    MathAcos("acos"),
    MathAcosh("acosh"),
    MathAsin("asin"),
    MathAsinh("asinh"),
    MathAtan("atan"),
    MathAtanh("atanh"),
    MathAtan2("atan2"),
    MathCbrt("cbrt"),
    MathCeil("ceil"),
    MathClz32("clz32"),
    MathCos("cos"),
    MathCosh("cosh"),
    MathExp("exp"),
    MathExpm1("expm1"),
    MathFloor("floor"),
    MathFround("fround"),
    MathHypot("hypot"),
    MathImul("imul"),
    MathLog("log"),
    MathLog1p("log1p"),
    MathLog10("log10"),
    MathLog2("log2"),
    MathMax("max"),
    MathMin("min"),
    MathPow("pow"),
    MathRandom("random"),
    MathRound("round"),
    MathSign("sign"),
    MathSin("sin"),
    MathSinh("sinh"),
    MathSqrt("sqrt"),
    MathTan("tan"),
    MathTanh("tanh"),
    MathTrunc("trunc"),

    NumberCtorIsFinite("isFinite"),
    NumberCtorIsInteger("isInteger"),
    NumberCtorIsNaN("isNaN"),
    NumberCtorIsSafeInteger("isSafeInteger"),
    NumberCtorParseFloat("parseFloat"),
    NumberCtorParseInt("parseInt"),
    NumberProtoToExponential("toExponential"),
    NumberProtoToFixed("toFixed"),
    NumberProtoToLocaleString("toLocaleString"),
    NumberProtoToPrecision("toPrecision"),
    NumberProtoToString("toString"),
    NumberProtoValueOf("valueOf"),

    ObjectCtorAssign("assign"),
    ObjectCtorCreate("create"),
    ObjectCtorDefineProperties("defineProperties"),
    ObjectCtorDefineProperty("defineProperty"),
    ObjectCtorEntries("entries"),
    ObjectCtorFreeze("freeze"),
    ObjectCtorFromEntries("fromEntries"),
    ObjectCtorGetOwnPropertyDescriptor("getOwnPropertyDescriptor"),
    ObjectCtorGetOwnPropertyDescriptors("getOwnPropertyDescriptors"),
    ObjectCtorGetOwnPropertyNames("getOwnPropertyNames"),
    ObjectCtorGetOwnPropertySymbols("getOwnPropertySymbols"),
    ObjectCtorGetPrototypeOf("getPrototypeOf"),
    ObjectCtorIs("is"),
    ObjectCtorIsExtensible("isExtensible"),
    ObjectCtorIsFrozen("isFrozen"),
    ObjectCtorIsSealed("isSealed"),
    ObjectCtorPreventExtensions("preventExtensions"),
    ObjectCtorSeal("seal"),
    ObjectCtorSetPrototypeOf("setPrototypeOf"),
    ObjectCtorValues("values"),
    ObjectProtoGetProto("__proto__", type = Type.Getter),
    ObjectProtoSetProto("__proto__", type = Type.Setter),
    ObjectProtoDefineGetter("defineGetter"),
    ObjectProtoDefineSetter("defineSetter"),
    ObjectProtoLookupGetter("lookupGetter"),
    ObjectProtoLookupSetter("lookupSetter"),
    ObjectProtoHasOwnProperty("hasOwnProperty"),
    ObjectProtoIsPrototypeOf("isPrototypeOf"),
    ObjectProtoPropertyIsEnumerable("propertyIsEnumerable"),
    ObjectProtoToLocaleString("toLocaleString"),
    ObjectProtoToString("toString"),
    ObjectProtoValueOf("valueOf"),

    ObjectPropertyIteratorProtoNext("next"),

    PromiseCtorAll("all"),
    PromiseCtorAllSettled("allSettled"),
    PromiseCtorResolve("resolve"),
    PromiseCtorReject("reject"),
    PromiseProtoCatch("catch"),
    PromiseProtoFinally("finally"),
    PromiseProtoThen("then"),

    ProxyCtorRevocable("revocable"),

    ReflectApply("apply"),
    ReflectConstruct("construct"),
    ReflectDefineProperty("defineProperty"),
    ReflectDeleteProperty("deleteProperty"),
    ReflectGet("get"),
    ReflectGetOwnPropertyDescriptor("getOwnPropertyDescriptor"),
    ReflectHas("has"),
    ReflectIsExtensible("isExtensible"),
    ReflectOwnKeys("ownKeys"),
    ReflectPreventExtensions("preventExtensions"),
    ReflectSet("set"),
    ReflectSetPrototypeOf("setPrototypeOf"),

    RegExpCtorGetSpecies("@@species", type = Type.Getter),
    RegExpProtoGetDotAll("dotAll", type = Type.Getter),
    RegExpProtoGetFlags("flags", type = Type.Getter),
    RegExpProtoGetGlobal("global", type = Type.Getter),
    RegExpProtoGetIgnoreCase("ignoreCase", type = Type.Getter),
    RegExpProtoGetMultiline("multiline", type = Type.Getter),
    RegExpProtoGetSource("source", type = Type.Getter),
    RegExpProtoGetSticky("sticky", type = Type.Getter),
    RegExpProtoGetUnicode("unicode", type = Type.Getter),
    RegExpProtoMatch("@@match"),
    RegExpProtoMatchAll("@@matchAll"),
    RegExpProtoReplace("@@replace"),
    RegExpProtoSearch("@@search"),
    RegExpProtoSplit("@@split"),
    RegExpProtoExec("exec"),
    RegExpProtoTest("test"),
    RegExpProtoToString("toString"),

    RegExpStringIteratorProtoNext("next"),

    SetCtorGetSymbolSpecies("@@species", type = Type.Getter),
    SetProtoGetSize("size", type = Type.Getter),
    SetProtoAdd("add"),
    SetProtoClear("clear"),
    SetProtoDelete("delete"),
    SetProtoEntries("entries"),
    SetProtoForEach("forEach"),
    SetProtoHas("has"),
    SetProtoValues("values"),

    SetIteratorProtoNext("next"),

    StringCtorFromCharCode("fromCharCode"),
    StringCtorFromCodePoint("fromCodePoint"),
    StringProtoAt("at"),
    StringProtoCharAt("charAt"),
    StringProtoCharCodeAt("charCodeAt"),
    StringProtoCodePointAt("codePointAt"),
    StringProtoConcat("concat"),
    StringProtoEndsWith("endsWith"),
    StringProtoIncludes("includes"),
    StringProtoIndexOf("indexOf"),
    StringProtoLastIndexOf("lastIndexOf"),
    StringProtoPadEnd("padEnd"),
    StringProtoPadStart("padStart"),
    StringProtoRepeat("repeat"),
    StringProtoReplace("replace"),
    StringProtoSlice("slice"),
    StringProtoSplit("split"),
    StringProtoStartsWith("startsWith"),
    StringProtoSubstring("substring"),
    StringProtoToLowerCase("toLowerCase"),
    StringProtoToString("toString"),
    StringProtoToUpperCase("toUpperCase"),
    StringProtoTrim("trim"),
    StringProtoTrimEnd("trimEnd"),
    StringProtoTrimStart("trimStart"),
    StringProtoValueOf("valueOf"),

    SymbolCtorFor("for"),
    SymbolCtorKeyFor("keyFor"),
    SymbolProtoToString("toString"),
    SymbolProtoToValue("toValue"),
    SymbolProtoSymbolToPrimitive("@@toPrimitive"),

    TypedArrayCtorFrom("from"),
    TypedArrayCtorOf("of"),
    TypedArrayProtoGetSymbolToStringTag("@@toStringTag", type = Type.Getter),
    TypedArrayProtoGetBuffer("buffer", type = Type.Getter),
    TypedArrayProtoGetByteLength("byteLength", type = Type.Getter),
    TypedArrayProtoGetByteOffset("byteOffset", type = Type.Getter),
    TypedArrayProtoGetLength("length", type = Type.Getter),
    TypedArrayProtoAt("at"),
    TypedArrayProtoCopyWithin("copyWithin"),
    TypedArrayProtoEntries("entries"),
    TypedArrayProtoEvery("every"),
    TypedArrayProtoFill("fill"),
    TypedArrayProtoFilter("filter"),
    TypedArrayProtoFind("find"),
    TypedArrayProtoFindIndex("findIndex"),
    TypedArrayProtoForEach("forEach"),
    TypedArrayProtoIncludes("includes"),
    TypedArrayProtoIndexOf("indexOf"),
    TypedArrayProtoJoin("join"),
    // TypedArrayProtoKeys("keys"),
    TypedArrayProtoLastIndexOf("lastIndexOf"),
    // TypedArrayProtoMap("map"),
    TypedArrayProtoReduce("reduce"),
    TypedArrayProtoReduceRight("reduceRight"),
    TypedArrayProtoReverse("reverse"),
    // TypedArrayProtoSet("set"),
    // TypedArrayProtoSlice("slice"),
    TypedArrayProtoSome("some"),
    // TypedArrayProtoSort("sort"),
    // TypedArrayProtoSubarray("subarray"),
    // TypedArrayProtoToString("toString"),
    // TypedArrayProtoValues("values"),

    // Non-standard builtins

    ClassObjectToString("toString"),
    ConsoleProtoLog("log"),
    GlobalId("id"),
    GlobalJvm("jvm"),
    GlobalInspect("inspect"),
    PackageProtoToString("toString");

    val key: PropertyKey get() = builtins[this]!!.key
    val length: Int get() = builtins[this]!!.length
    val handle: MethodHandle get() = builtins[this]!!.handle

    enum class Type(val methodType: MethodType) {
        Normal(MethodType.methodType(JSArguments::class.java)),
        Getter(MethodType.methodType(JSValue::class.java)),
        Setter(MethodType.methodType(JSValue::class.java)),
    }

    data class BuiltinInfo(
        val key: PropertyKey,
        val length: Int,
        val handle: MethodHandle,
    )

    companion object {
        internal val builtins = mutableMapOf<Builtin, BuiltinInfo>()

        internal fun registerBuiltinInfo(
            builtin: Builtin,
            name: PropertyKey,
            length: Int,
            handle: MethodHandle
        ) {
            builtins[builtin] = BuiltinInfo(name, length, handle)
        }
    }
}
