package me.mattco.reeva.runtime

enum class SlotName {
    ArrayBufferData,
    ArrayBufferByteLength,
    ArrayBufferDetachKey,
    ArrayLength,
    BigIntData,
    BooleanData,
    ByteLength,
    ByteOffset,
    ContentType,
    DateValue,
    Description,
    ErrorData,
    MapData,
    NumberData,
    OriginalSource,
    OriginalFlags,
    ParameterMap,
    PromiseFulfillReactions,
    PromiseIsHandled,
    PromiseState,
    PromiseRejectReactions,
    PromiseResult,
    ProxyHandler,
    ProxyTarget,
    RegExpMatcher,
    SetData,
    StringData,
    SymbolData,
    TypedArrayKind, // non-standard
    TypedArrayName,
    ViewedArrayBuffer,
}
